# mkconda requires a current GIT_TOKEN on TravisCI kutaslab/mkconda
env:
    - PACKAGE_NAME: mkconda   # for the conda_upload.sh deploy script
    # - CROOT: /tmp/mkconda/conda-bld
language: minimal
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
install:
    - conda install -q conda-build conda-verify
    - conda clean --all
    - mkdir -p /tmp/mkconda/conda-bld
    - cp -r ./conda/conda-bld/* /tmp/mkconda/conda-bld
    # - conda build conda -c kutaslab -c defaults -c conda-forge
    # - conda create --name mkconda_env mkconda -c local -c kutaslab -c defaults -c conda-forge
    # build env from recipe file snapshot 
    - conda create --name run_env --file ./conda/mkconda_env_recipe.txt
    - conda activate run_env
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
    - python -c 'import matplotlib; print(matplotlib.__version__)'
    - python -c 'import mkpy; print(mkpy.__version__)'
    - python -c 'import fitgrid; print(fitgrid.__version__)'
after_success:
    - git clone https://github.com/kutaslab/mkpy pkgs/mkpy
    - cd pkgs/mkpy
    - pytest
    - cd ../..

    - git clone https://github.com/kutaslab/spudtr pkgs/spudtr
    - cd pkgs/spudtr
    - pytest
    - cd ../..

    - git clone https://github.com/kutaslab/fitgrid pkgs/fitgrid
    - cd pkgs/fitgrid
    - pytest
    - cd ../..
    - pwd
    - ls -l

    - conda deactivate   # fall back to build env
before_deploy:
    - conda install anaconda-client
    - conda list
deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./ci/conda_upload.sh
      on:
          all_branches: true
