package:
  name: mkconda
  version: "0.1.0"

build:
  noarch: python
  string: {{environ.get("GIT_ABBREV_COMMIT", "no_git_abbrev_commit")}}_0

requirements:
  run:
    - blas=*=*mkl
    - fitgrid
    - spudtr
    - mkpy
    - jupyterlab
    - numba
    - spyder
    - rapids
    # - cudatoolkit-dev
    - pytorch
    - r-tidyverse
    - r-irkernel
    - firefox

test:
  imports:
    - mkpy
    - spudtr
    - fitgrid
